change functions declarations

diff --git a/install-splinter b/install-splinter
--- a/install-splinter
+++ b/install-splinter
@@ -8,7 +8,7 @@ splinter_archive="https://github.com/marcomc/splinter/archive/master.zip"
 base_profile="base"
 base_profile_example="base-example"
 
-shell_join() {
+function shell_join {
   local arg
   printf "%s" "$1"
   shift
@@ -18,15 +18,13 @@ shell_join() {
   done
 }
 
-abort() {
+function abort {
   printf "%s\n" "$1"
   exit 1
 }
 
-execute() {
-  if ! "$@"; then
-    abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
-  fi
+function execute {
+  "$@" || abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
 }
 
 if [ -d "${splinter_dir}" ];then
